// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swkespyozgqagzntuplj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3a2VzcHlvemdxYWd6bnR1cGxqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NDM3MDIsImV4cCI6MjA3MzExOTcwMn0.69ByJyRlJ3ZrZBoC1MeORWg-wKuyhBEnZtvOm2Wvvv4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});